version: "3.9"
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql_data_container
    restart: always
    ports:
       - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
volumes:
  dbdata:
