version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DB_PASSWORD: abc123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: abc123
  
  book-info-service:
    image: miverboven/book-info-service-ex
    ports:
      - '8051:8051'
    networks:
      - my-network

volumes:
 mysql_data_container:
